spring:
  datasource:
    url: jdbc:mysql://localhost:3306/servicios
    username: root
    password: 
  mvc:
    favicon:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
